language: java

sudo: required

services:
  - docker

jdk:
  - openjdk11

git:
  depth: 3

before_install:
  - chmod +x gradlew

after_success:
  - docker build -t wernerw/ww-net:$TRAVIS_BRANCH . && docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
