version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "e7:16:bf:20:ac:9c:2b:a1:6b:62:23:ea:a7:c0:e2:79"
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Build
          command: |
            yarn install --frozen-lockfile
            yarn build
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn            
      - run:
          name: Deploy
          command: |
            ssh -t wolfgang_werner@$IPFS_NODE "rm -rf deploy"
            ssh -t wolfgang_werner@$IPFS_NODE "ipfs pin rm < .hash"
            scp -r build/ wolfgang_werner@$IPFS_NODE:/home/wolfgang_werner/deploy 
            ssh -t wolfgang_werner@$IPFS_NODE "ipfs add --pin -r -Q deploy > .hash"

            npx cfcli -h
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build -t wwerner/ww.net:$CIRCLE_BRANCH .
