version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            yarn install
            yarn build
      # TODO: cache dependencies
      - run:
          command: |
            npx jscli -h
            npx cfcli -h
      - run: docker build -t wwerner/ww.net:$CIRCLE_BRANCH .
